version: 1

resources:
  single-node:
    count: 1
    type: node
    requires:
      io.archspec:
        cpu.target: amd64

tasks:
- name: task-1
  command:
    - bash
    - -c
    - "echo Starting task 1; sleep 3; echo Finishing task 1"
  resources: single-node

- name: task-2
  command:
      - bash
      - -c
      - "echo Starting task 2; sleep 3; echo Finishing task 2"

  resources: single-node
