version: 1
requires:
  io.archspec:
    cpu.target: amd64

tasks:
- name: task-1
  command:
    - bash
    - -c
    - "echo Starting task 1; sleep 3; echo Finishing task 1"

  resources:
    count: 1
    type: node

- name: task-2
  depends_on: ["task-1"]

  # This is an example of a custom "task-level' requires
  requires:
    hardware.gpu.available: "yes"
  command:
      - bash
      - -c
      - "echo Starting task 2; sleep 3; echo Finishing task 2"

  resources:
    count: 1
    type: node