version: 1
resources:
- count: 4
  type: node
  with:
  - count: 1
    label: fractal-descriptive
    type: slot
    with:
    - count: 4
      type: core

task:
  transform:
    - step: write
      filename: install.sh
    - step: submit
      filename: install.sh
      wait: true
    - step: write
      filename: job.sh
    - step: submit
      filename: job.sh
      
  scripts: 
    - name: install.sh
      content: |
        #!/bin/bash
        echo "This is an install step"

    - name: job.sh
      content: |
        #!/bin/bash
        echo "This is task ${FLUX_TASK_RANK}"
        if [[ "${FLUX_TASK_RANK}" == "0" ]]; then
          echo "Hello I am the leader: $(hostname)"
        else
          echo "Hello I am a follower: $(hostname)"
        fi 
        
  count:
    per_slot: 1
  resources:
    hardware:
      hardware.gpu.available: 'no'
    software:
      go: "1.20"
    io.archspec:
      cpu.target: amd64
    os:
      os.name: Ubuntu 22.04.3 LTS
      os.release: 22.04.3
      os.vendor: ubuntu
  slot: fractal-descriptive
