name: test jobspec
on:
  pull_request: []

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: ['fluxrm/flux-sched:jammy']

    container:
      image: ${{ matrix.container }}
      options: "--platform=linux/amd64 --user root -it --init"

    name: ${{ matrix.container }}
    steps:
      - name: Make Space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jobspec
        run: |
          apt-get update && apt-get install -y python3-pip
          pip3 install .

      # Any additional examples added here will be tested
      - name: Start Flux and Run Examples
        run: |
          which jobspec
          flux start jobspec run ./examples/hello-world-jobspec.yaml
          flux start jobspec run ./examples/group-with-group.yaml
          flux start jobspec run ./examples/task-with-group.yaml
          flux start python3 ./examples/flux/receive-job.py

          # We don't need flux for satisfies
          jobspec satisfy ./examples/subsystems/jobspec-spack-subystem-unsatisfied.yaml --subsystem-dir ./examples/subsystems || echo "Correct"
          jobspec satisfy ./examples/subsystems/jobspec-spack-subystem-satisfied.yaml --subsystem-dir ./examples/subsystems
